vulnerabilities:
  # ------------------------------------------------------------------------
  # Distroless Debian (libexpat)
  # Waiting for a Distroless image rebuilt with libexpat >= 2.8.2.
  # ------------------------------------------------------------------------

  - id: CVE-2025-59375
    expired_at: 2026-10-31
    statement: Waiting for a Distroless image rebuilt with patched libexpat.

  - id: CVE-2026-25210
    expired_at: 2026-10-31
    statement: Waiting for a Distroless image rebuilt with patched libexpat.

  - id: CVE-2026-45186
    expired_at: 2026-10-31
    statement: Waiting for a Distroless image rebuilt with patched libexpat.

  - id: CVE-2026-56131
    expired_at: 2026-10-31
    statement: Waiting for a Distroless image rebuilt with patched libexpat.

  - id: CVE-2026-56408
    expired_at: 2026-10-31
    statement: Waiting for a Distroless image rebuilt with patched libexpat.
