vulnerabilities:
  - id: CVE-2026-41842
    expired_at: 2026-09-30
    statement: Waiting for Spring Boot release including Spring Framework 6.2.19.

  - id: CVE-2026-41845
    expired_at: 2026-09-30
    statement: Waiting for Spring Boot release including Spring Framework 6.2.19.

  - id: CVE-2026-41850
    expired_at: 2026-09-30
    statement: Waiting for Spring Boot release including Spring Framework 6.2.19.

    