package com.example.flashcards;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class FlashcardsApplicationTests {

  @Test
  void contextLoads() {
    // Test generated by Spring Boot to verify that the application context loads
    // successfully.
  }

}
