name: Distroless Watch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  watch:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0

      - name: Setup git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Install crane
        id: install
        run: |
          ci-scripts/install-crane.sh

      - name: Run digest check
        id: check
        run: |
          ci-scripts/check-docker-image-latest.sh

      - name: Create branch with updated digest
        if: steps.check.outputs.digest_changed == 'true'
        id: branch
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          EXISTING=$(gh pr list \
            --base develop \
            --search "in:title chore: distroless image updated" \
            --json number \
            --jq length)

          if [ "$EXISTING" -gt 0 ]; then
            echo "Existing PR detected, skipping"
            echo "skip_pr=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          BRANCH="chore/distroless-update-$(date +%s)"
          git checkout -b $BRANCH
          DIGEST="${{ steps.check.outputs.digest_value }}"

          echo "$DIGEST" > ci-scripts/.distroless-java17-debian13.digest
          sed -i "s|FROM gcr.io/distroless/java17-debian13:nonroot.*|FROM gcr.io/distroless/java17-debian13:nonroot@$DIGEST|" Dockerfile
          git add \
            ci-scripts/.distroless-java17-debian13.digest \
            Dockerfile

            git diff --cached --quiet && {
              echo "No changes detected"
              echo "skip_pr=true" >> $GITHUB_OUTPUT
              exit 0
            }

          git commit -m "chore: update distroless digest"
          git push origin $BRANCH
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
      
      - name: Create PR
        if: steps.check.outputs.digest_changed == 'true' && steps.branch.outputs.skip_pr != 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          BRANCH="${{ steps.branch.outputs.branch }}"

          gh pr create \
            --base develop \
            --head "$BRANCH" \
            --title "chore: distroless image updated" \
            --body "Automatic update of distroless base image.\n\nDigest updated -> possible security fixes available.\n\nActions recommended:\n- Run pipeline\n- Verify Trivy results\n- Check if CVEs can be removed from .trivyignore"
   