.trivy:
  image:
    name: $TRIVY_IMAGE
    entrypoint: [""]
  cache:
    - key: trivy-db
      paths:
        - .trivycache/
      policy: pull-push
  variables:
    TRIVY_CACHE_DIR: "$CI_PROJECT_DIR/.trivycache"

.trivy-with-maven:
  extends: .trivy
